baseURL = "http://localhost:1313"
languageCode = "en"
title = "Brinsley Morrison"
_enabled_editors = ["visual", "content"]

defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    languageCode = 'en-GB'

    weight = 1
    title = "Brinsley Morrison"
    contentDir = "content/en"

    [languages.en.params]
        date_format = "02 Jan 2006"
    

  [languages.ja]
    languageName = "日本語"
    languageCode = 'ja'

    weight = 2
    title = "森沢淋"
    contentDir = "content/ja"

    [languages.ja.params]
      date_format = "2006年01月02日"

  [languages.zh]
    languageName = "中文"
    languageCode = 'zh'

    weight = 3
    title = "林泽"
    contentDir = "content/zh"

    [languages.zh.params]
      date_format = "2006年01月02日"


[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'

[markup.goldmark.renderer]
hardWraps = true
unsafe = true

[permalinks]
posts = "/compositions/:title/"
projects = "/blog/:title/"

[params]
# Use local assets for development instead of CDN
jsdelivr_base_url = ""
